version: "3.9"
services:
  nginx-php:
    build: ./docker
    working_dir: /app
    ports:
      - 8081:80
    volumes:
      - .:/app
      - ./xhprof.ini:/usr/local/etc/php/conf.d/docker-php-ext-xhprof.ini
      - ./xhprof:/app/public/xhprof
      - ./tmp:/tmp/xhprof
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      PHP_DISPLAY_ERRORS: 1
  mysql8:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: sales
      MYSQL_ROOT_PASSWORD: 123456