version: "3.8"
services:
  php:
    image: webdevops/php-nginx-dev:8.1-alpine
    volumes:
      - .:/app
    ports:
      - ${SERVER_PORT}:80
    env_file:
      - .env
      
  mariadb:
    image: mariadb:10.7.4-focal
    ports:
      - ${DB_PORT}:3306
    env_file:
      - .env
  