version: "3.9"
services:
  nginx-php:
    build: ./docker
    ports:
      - 8081:80
    volumes:
      - .:/app
      - ./xhprof.ini:/usr/local/etc/php/conf.d/docker-php-ext-xhprof.ini
      - ./xhprof:/app/public/xhprof
      - ./tmp:/tmp/xhprof
    environment:
      - WEB_DOCUMENT_ROOT=/app/public